export const plans = [
  {
    name: 'Free',
    price: '$0',
    period: '/ Month',
    badge: null,
    description: 'Perfect for trying out Jet Prompt Optimizer.',
    features: [
      '5 optimizations per day',
      'Basic Fast Rewrite engine (simple clean-ups, no schema validation)',
      'Standard output formatting',
      'Community support',
      'No login required'
    ],
    cta: 'Subscribe',
    featured: false,
    bgColor: 'bg-white',
    borderColor: 'border-gray-200',
    textColor: 'text-gray-900',
    descColor: 'text-gray-600',
    featureColor: 'text-gray-700',
    checkColor: 'text-orange-500',
    buttonBg: 'bg-white border-2 border-gray-300',
    buttonText: 'text-gray-800',
    buttonHover: 'hover:bg-gray-50'
  },
  {
    name: 'Essential',
    price: '$49.95',
    period: '/ Month',
    badge: null,
    mostPopular: true,
    description:
      'For creators and everyday users who want structured prompts that consistently perform.',
    features: [
      'Unlimited optimizations',
      'Structured Prompt Writer for guided prompt design',
      'Prompt history & versioning (never lose a winning prompt)',
      'Multi-system prompt builder (reuse prompts across tools/models)',
      'AI workflow presets',
      'Optional API access',
      'Priority + live chat support'
    ],
    cta: 'Subscribe',
    featured: true,
    bgColor: 'bg-jet-blue',
    textColor: 'text-white',
    descColor: 'text-indigo-100',
    featureColor: 'text-indigo-50',
    checkColor: 'text-pink-400',
    buttonBg: 'bg-orange-500',
    buttonText: 'text-white',
    buttonHover: 'hover:bg-orange-600'
  },
  {
    name: 'Pro',
    price: '$95.95',
    period: '/ Month',
    badge: null,
    description:
      'For consultants, power users, and automation builders shipping production-grade workflows.',
    features: [
      'Everything in Essential, plus:',
      'Schema-Validated Writer (full validation loops & format enforcement)',
      'Master generation mode enabled',
      'Enigma AI engine for deeper reasoning & rewrite logic',
      'Up to 50 high-priority optimizations/day',
      'High-Context Workflow Mode',
      'Multi-prompt orchestration',
      'Chaining + validation steps',
      'Custom tones & styles',
      'Priority support (fast-track responses)'
    ],
    cta: 'Subscribe',
    featured: false,
    bgColor: 'bg-white',
    borderColor: 'border-gray-200',
    textColor: 'text-gray-900',
    descColor: 'text-gray-600',
    featureColor: 'text-gray-700',
    checkColor: 'text-orange-500',
    buttonBg: 'bg-white border-2 border-gray-300',
    buttonText: 'text-gray-800',
    buttonHover: 'hover:bg-gray-50'
  },
  {
    name: 'Premium / Enterprise',
    price: 'Schedule a Call',
    period: '',
    badge: null,
    description: 'For teams and enterprises that need governance, analytics, and scale.',
    features: [
      'Everything in Pro, plus:',
      'Extended context length and max tokens per request',
      'Multi-prompt orchestration and full workflow chaining',
      'Organization-wide prompt libraries & role-based access',
      'Central analytics dashboard: usage, quality, and cost insights',
      'Enterprise-grade API with priority limits',
      'Security, compliance, and audit trails',
      'Dedicated success manager & onboarding'
    ],
    cta: 'Subscribe',
    featured: false,
    bgColor: 'bg-white',
    borderColor: 'border-gray-200',
    textColor: 'text-gray-900',
    descColor: 'text-gray-600',
    featureColor: 'text-gray-700',
    checkColor: 'text-orange-500',
    buttonBg: 'bg-white border-2 border-gray-300',
    buttonText: 'text-gray-800',
    buttonHover: 'hover:bg-gray-50'
  }
];
