  export const plans = [
    {
      name: 'Free',
      price: '$0',
      period: '/ month',
      badge: null,
      description: 'Perfect for beginners exploring prompt optimization.',
      features: [
        '5 optimizations per day',
        'Standard output formatting',
        'Community support',
        'No login required'
      ],
      cta: 'Subscribe',
      featured: false,
      bgColor: 'bg-white',
      borderColor: 'border-gray-200',
      textColor: 'text-gray-900',
      descColor: 'text-gray-600',
      featureColor: 'text-gray-700',
      checkColor: 'text-orange-500',
      buttonBg: 'bg-white border-2 border-gray-300',
      buttonText: 'text-gray-800',
      buttonHover: 'hover:bg-gray-50'
    },
    {
      name: 'Starter',
      price: '$9',
      period: '/ month',
      badge: '-17%',
      mostPopular: true,
      description: 'Ideal for individuals and small projects getting started.',
      features: [
        '25 optimizations per day',
        'Enhanced output quality',
        'Email support',
        'Export functionality'
      ],
      cta: 'Subscribe',
      featured: true,
      bgColor: 'bg-jet-blue',
      textColor: 'text-white',
      descColor: 'text-indigo-100',
      featureColor: 'text-indigo-50',
      checkColor: 'text-pink-400',
      buttonBg: 'bg-orange-500',
      buttonText: 'text-white',
      buttonHover: 'hover:bg-orange-600'
    },
    {
      name: 'Pro',
      price: '$17',
      period: '/ month',
      badge: '-20%',
      description: 'The complete suite — build expert-level prompts and AI instructions.',
      features: [
        'Unlimited optimizations',
        'Enigma AI',
        'AI workflow presets',
        'Multi system prompt builder',
        'Prompt history & versioning',
        'API access (optional)',
        'Priority + live chat support'
      ],
      cta: 'Subscribe',
      featured: false,
      bgColor: 'bg-white',
      borderColor: 'border-gray-200',
      textColor: 'text-gray-900',
      descColor: 'text-gray-600',
      featureColor: 'text-gray-700',
      checkColor: 'text-orange-500',
      buttonBg: 'bg-white border-2 border-gray-300',
      buttonText: 'text-gray-800',
      buttonHover: 'hover:bg-gray-50'
    },
    {
      name: 'Enterprise',
      price: '$49',
      period: '/ month',
      badge: '-17%',
      description: 'Advanced tools for teams and organizations with custom needs.',
      features: [
        'Everything in Pro',
        'Team collaboration (up to 10)',
        'Custom AI model training',
        'Dedicated account manager',
        'SLA guarantee',
        'Advanced security features',
        'Custom integrations',
        'White-label options'
      ],
      cta: 'Subscribe',
      featured: false,
      bgColor: 'bg-white',
      borderColor: 'border-gray-200',
      textColor: 'text-gray-900',
      descColor: 'text-gray-600',
      featureColor: 'text-gray-700',
      checkColor: 'text-orange-500',
      buttonBg: 'bg-white border-2 border-gray-300',
      buttonText: 'text-gray-800',
      buttonHover: 'hover:bg-gray-50'
    }
  ];
